#!/bin/sh

conf_admin_ip=$(ifconfig $(netstat -r | grep default | awk '{ print $4 }') | grep 'inet' | awk -F ' ' '{ print $2 }')
CONFFILE="/usr/chunter/etc/chunter.conf"
if [ ! -f $CONFFILE ]
then
    echo "Creating new configuration from example file."
    if [ "$conf_admin_ip" = "" ]
    then
        cp ${CONFFILE}.example ${CONFFILE}
    else
        sed "s/^ip = 127.0.0.1:4200/ip=$conf_admin_ip:4200/" ${CONFFILE}.example > ${CONFFILE}
    fi
else
    echo "Please make sure you update your config according to the update manual!"
    #/opt/local/fifo-sniffle/share/update_config.sh ${CONFFILE}.example ${CONFFILE} > ${CONFFILE}.new &&
    #    mv ${CONFFILE} ${CONFFILE}.old &&
    #    mv ${CONFFILE}.new ${CONFFILE}

fi